
import './style.css'
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/free-mode';
import 'swiper/css/scrollbar';


// import required modules
import { FreeMode, Scrollbar, Mousewheel } from 'swiper/modules';
import { useState } from 'react';
import Footer from '../../components/footer/Footer';
const Terms = () => {


    let termsList = [
        {
            h1: 'GENERAL TERMS AND CONDITIONS',
            p: ['AT INTERVALS, WE MAY OFFER FOR SALE DIGITAL ENTITIES ("COMPANY NFTS"), ALTERNATIVE DIGITAL VALUABLES ("DIGITAL ASSETS"), AND/OR TANGIBLE COMMODITIES COLLECTIVELY LABELED AS "COMPANY PRODUCTS" VIA OUR DIGITAL REALM. OUR DIGITAL SPACE IS TAILORED FOR INDIVIDUALS AGED 18 AND ABOVE. ACCESS TO OUR DIGITAL REALM IS RESTRICTED FOR THOSE UNDER 18. TO PARTAKE IN THE PROCUREMENT OR RECEPTION OF COMPANY PRODUCTS, YOU COMMIT TO ADHERENCE TO THE SPECIFIC TERMS AND CONDITIONS LINKED TO EACH DISTINCT COMPANY PRODUCT, ALONGSIDE THESE OVERARCHING TERMS. PAYMENTS TRANSACTED THROUGH THIRD-PARTY PARTNERS FOR COMPANY PRODUCTS ARE CONTINGENT ON DISTINCT TERMS AND CONDITIONS, IF ANY, OUTLINED BY SAID PARTNERS. YOU RECOGNIZE OUR LACK OF CONTROL OVER THESE FINANCIAL DEALINGS, WITH NO CAPABILITY TO REVERSE TRANSACTIONS, ABSOLVING US OF ANY LIABILITY TO YOU OR ANY THIRD PARTY FOR CONSEQUENTIAL CLAIMS OR DAMAGES STEMMING FROM WEBSITE TRANSACTIONS VIA THIRD-PARTY SERVICES.', 'MOREOVER, WE MAY SPORADICALLY INTRODUCE COMPANY PRODUCTS TO AUCTION THROUGH DIVERSE BIDDING PROCESSES ("AUCTION"). YOUR COMMITMENT EXTENDS TO COMPLIANCE WITH THE DIVERSE RULES AND REGULATIONS GOVERNING EACH AUCTION. UNLESS SPECIFIED OTHERWISE, FUNDS TIED TO UNSUCCESSFUL AUCTION BIDS WILL BE SECURELY HELD, WITH PROMPT REFUNDS. FOR VICTORIOUS AUCTIONS, REDEMPTION OF THE CORRESPONDING COMPANY PRODUCT IS AT YOUR DISCRETION WITHIN A REASONABLE TIMEFRAME.', 'OUR DIGITAL SPHERE IS OUR EXCLUSIVE DOMAIN, ENCOMPASSING SOURCE CODE, DATABASES, FUNCTIONALITY, SOFTWARE, WEBSITE DESIGNS, AUDIO-VISUAL COMPONENTS, TEXT, AND GRAPHICS (COLLECTIVELY, THE "CONTENT"), ALONGSIDE TRADEMARKS, SERVICE MARKS, AND LOGOS (THE "MARKS"). THESE ELEMENTS ARE EITHER PROPRIETARY OR LICENSED TO US, FORTIFIED BY COPYRIGHT, TRADEMARK, AND AN ARRAY OF INTELLECTUAL PROPERTY RIGHTS. THE CONTENT AND MARKS ARE SHARED ON THE PLATFORM "AS IS" FOR INFORMATIONAL AND PERSONAL USE EXCLUSIVELY. ABSENT EXPRESS PERMISSION IN THESE TERMS OR UNDER A PERTINENT LICENSE ON OUR PLATFORM, NO FACET OF THE WEBSITE, CONTENT, OR MARKS MAY BE REPLICATED, AGGREGATED, REPUBLISHED, UPLOADED, PUBLICLY DISPLAYED, ENCODED, TRANSLATED, TRANSMITTED, DISTRIBUTED, SOLD, LICENSED, OR OTHERWISE HARNESSED FOR COMMERCIAL PURPOSES WITHOUT OUR EXPLICIT WRITTEN CONSENT. IF DEEMED ELIGIBLE, A FINITE LICENSE IS BESTOWED FOR ACCESSING AND UTILIZING THE PLATFORM SOLELY FOR PERSONAL, NON-COMMERCIAL PURSUITS. ALL RIGHTS TO THE PLATFORM, CONTENT, AND MARKS ARE RESERVED BY US.']
        },
        {
            h1: 'DIGITAL ASSETS',
            p: ['DIGITAL ASSETS AVAILABLE ON OUR PLATFORM ARE OPEN TO BUYING, SELLING, AND TRADING ON EXTERNAL MARKETPLACES OR TRADING PLATFORMS (REFERRED TO AS "SECONDARY TRANSACTIONS"). THE TERMS AND CONDITIONS OF THESE PLATFORMS GOVERN SECONDARY TRANSACTIONS. WE DO NOT INVOLVE OURSELVES IN SECONDARY TRANSACTIONS AND PROVIDE NO ASSURANCES REGARDING THE AVAILABILITY OR FUNCTIONALITY OF THESE EXTERNAL SITES. YOUR USE OF SUCH PLATFORMS IS ENTIRELY AT YOUR OWN RISK, AND WE DISCLAIM ANY RESPONSIBILITY FOR POTENTIAL CLAIMS OR DAMAGES ARISING FROM YOUR SECONDARY TRANSACTIONS OR USE OF EXTERNAL PLATFORMS.', 'UNLESS EXPLICITLY COMMUNICATED BY US, YOU BEAR SOLE RESPONSIBILITY FOR SETTLING ANY AND ALL TAXES—COVERING INCOME, CAPITAL GAINS, SALES, USE, VALUE-ADDED, AND OTHER TAXES, DUTIES, AND ASSESSMENTS—THAT MAY BE CLAIMED OR IMPOSED BY ANY GOVERNMENTAL AUTHORITY ("TAXES") IN CONNECTION WITH DIGITAL ASSETS ACQUIRED OR RECEIVED BY YOU. THIS INCLUDES TAXES RELATED TO OWNERSHIP, TRANSFER, PURCHASE, RECEIPT, OR SALE OF A COMPANY NFT.', 'THESE ASSETS ARE ELIGIBLE TO PARTICIPATE IN COMPANY ACTIVITIES LINKED TO DIGITAL ASSET OWNERSHIP. IN THE EVENT OF FURTHER CHANGES TO THE OPERATIONAL RULES OF THE UNDERLYING SOFTWARE PROTOCOL OF A RELEVANT BLOCKCHAIN NETWORK RESULTING IN TWO DISTINCT BRANCHES, BOTH PARTIES ACKNOWLEDGE AND AGREE THAT THE COMPANY MAY, AT ITS DISCRETION, DECIDE TO SUPPORT OR CEASE SUPPORTING THE COMPANY NFTS ON EITHER BRANCH OF THE FORKED SOFTWARE PROTOCOL. YOU ACKNOWLEDGE THAT WE ASSUME NO LIABILITY, OBLIGATION, OR RESPONSIBILITY CONCERNING THE OPERATION OF UNDERLYING SOFTWARE PROTOCOLS OR AN UNSUPPORTED BRANCH OF A FORKED SOFTWARE PROTOCOL, INCLUDING, BUT NOT LIMITED TO, ANY VIABLE PROOF OF WORK ETHEREUM FORK. YOU EXPLICITLY ACKNOWLEDGE AND ASSUME THE ASSOCIATED RISKS.']
        },
        {
            h1: 'PHYSICAL PRODUCTS',
            p: ["AT VARIOUS INTERVALS, WE MAY INTRODUCE PHYSICAL PRODUCTS EITHER FOR SALE OR AS COMPLIMENTARY OFFERINGS. IT IS CRUCIAL TO RECOGNIZE THAT THE TERMS AND CONDITIONS ASSOCIATED WITH THESE RELEASES ARE SOLELY WITHIN THE DISCRETION OF THE COMPANY. BY ENGAGING IN SUCH RELEASES, YOU COMMIT TO ABIDING BY ANY PERTINENT TERMS AND CONDITIONS. THE COMPANY PROVIDES NO ASSURANCES OR WARRANTIES REGARDING THE PHYSICAL PRODUCTS. NOTWITHSTANDING THIS, IN THE EVENT OF DEFECTS OR ISSUES, THE COMPANY, AT ITS SOLE DISCRETION, WILL ASSESS ON A CASE-BY-CASE BASIS WHETHER TO IMPLEMENT ANY CORRECTIVE MEASURES. UNLESS EXPLICITLY COMMUNICATED OTHERWISE BY US, THERE IS NO PROVISION FOR THE RETURN, REFUND, OR EXCHANGE OF ANY PURCHASED PHYSICAL PRODUCTS. HOWEVER, IN THE CASE OF THE GOLDEN SKATEBOARD, THE COMPANY WILL EXERT COMMERCIALLY REASONABLE EFFORTS TO ADDRESS DEFECTS ON A CASE-BY-CASE BASIS.", "SOME PHYSICAL PRODUCTS WILL BE EQUIPPED WITH A CRYPTOGRAPHIC CHIP ('AKGR CHIP'), LINKING THE PHYSICAL ITEM TO A DIGITAL TOKEN THROUGH 'AKGR CHIP' SCANNING FOR AUTHENTICATION AND PROOF OF OWNERSHIP. THE COMPANY DOES NOT GUARANTEE THE ABSENCE OF DEFECTS RELATED TO THE AKGR CHIP. CONSIDERING THE FINITE AVAILABILITY OF 'AKGR CHIPS', IF YOUR 'AKGR CHIP' IS DEFECTIVE, THE COMPANY DOES NOT ENSURE REPLACEMENT.", "THE COMPANY ASSUMES NO LIABILITY FOR ANY FAILURE TO DELIVER OR FOR DELAYS RESULTING FROM CIRCUMSTANCES BEYOND OUR REASONABLE CONTROL, ENCOMPASSING, BUT NOT LIMITED TO, STRIKES, INDUSTRIAL DISPUTES, BREAKDOWN OF SYSTEMS OR NETWORK ACCESS, FLOODS, FIRES, EXPLOSIONS, OR ACCIDENTS LEADING TO DAMAGE OR DEFECTS IN THE GOODS"]
        },
        {
            h1: 'COVENANTS AND RESTRICTIONS',
            p: ["TO GAIN ACCESS TO THE WEBSITE, YOU COMMIT TO REFRAINING FROM, AND YOU WILL NOT AUTHORIZE ANY THIRD PARTY TO ENGAGE IN OR ATTEMPT ANY OF THE FOLLOWING ACTIONS WITHOUT OBTAINING OUR PRIOR WRITTEN CONSENT: (1) EVADING, DISRUPTING, DISABLING, OR INTERFERING WITH THE WEBSITE, ITS SERVERS, OR CONNECTED NETWORKS, OR ANY SECURITY FEATURES, INCLUDING THE UPLOADING OR TRANSMISSION OF VIRUSES, TROJAN HORSES, OR SIMILAR HARMFUL MATERIALS; (2) VIOLATING ANY APPLICABLE LOCAL, STATE, NATIONAL, OR INTERNATIONAL LAWS OR REGULATIONS, INCLUDING THOSE ENFORCED BY THE U.S. DEPARTMENT OF TREASURY'S OFFICE OF FOREIGN ASSETS CONTROL (“OFAC”), OR PARTICIPATING IN ACTIVITIES RELATED TO PROCEEDS FROM UNLAWFUL ACTIVITIES; (3) ATTEMPTING TO BYPASS THE PROTECTIVE MEASURES OR ACCESS RESTRICTIONS OF THE WEBSITE; (4) UTILIZING COMPANY PRODUCTS FOR ADVERTISING, SELLING, OR PURCHASING GOODS OR SERVICES FOR PURPOSES NOT EXPLICITLY AUTHORIZED HEREIN OR UNDER THE APPLICABLE LICENSE AGREEMENT; (5) DECODING, DECOMPILING, DISASSEMBLING, OR REVERSE ENGINEERING ANY SOFTWARE INTEGRAL TO THE WEBSITE; (6) UTILIZING COMPANY PRODUCTS TO SUPPORT CRIMINAL ACTIVITIES, CONCEAL ECONOMIC ACTIVITY, LAUNDER MONEY, OR FINANCE TERRORISM; (7) REPLICATING OR MODIFYING THE WEBSITE’S SOFTWARE OR CODE; AND (8) CONDUCTING FINANCIAL ACTIVITIES REQUIRING REGISTRATION OR LICENSING, SUCH AS CREATING, LISTING, OR BUYING SECURITIES, COMMODITIES, OPTIONS, REAL ESTATE, OR DEBT INSTRUMENTS.", "PARTICIPATING IN TRANSACTIONS WITH ANY INDIVIDUAL, ENTITY, OR COUNTRY PROHIBITED BY APPLICABLE EXPORT CONTROL AND SANCTIONS LAWS AND REGULATIONS OF THE UNITED STATES AND OTHER RELEVANT GOVERNMENTAL AUTHORITIES IS STRICTLY FORBIDDEN. THIS ENCOMPASSES ADHERENCE TO THE U.S. EXPORT ADMINISTRATION REGULATIONS AND U.S. SANCTIONS REGULATIONS (“EXPORT CONTROL AND SANCTIONS LAWS”), EXPLICITLY PROHIBITING TRANSACTIONS WITH INDIVIDUALS FROM COUNTRIES SUBJECT TO U.S. SANCTIONS (CURRENTLY, CUBA, IRAN, SYRIA, NORTH KOREA, AND SPECIFIED REGIONS OF UKRAINE: CRIMEA, DONETSK, AND LUHANSK), OR INDIVIDUALS LISTED ON THE U.S. TREASURY DEPARTMENT’S SPECIALLY DESIGNATED NATIONALS OR OTHER SANCTIONS LISTS. IF ANY OF THESE RESTRICTIONS APPLY, YOU ARE NOT PERMITTED TO PURCHASE COMPANY PRODUCTS OR ENGAGE IN TRANSACTIONS WITH US THROUGH THE WEBSITE OR ANY OTHER MEANS. IN THE EVENT OF A VIOLATION OF THIS PROVISION, WE RETAIN THE RIGHT, TO THE FULLEST EXTENT POSSIBLE, TO CANCEL ANY TRANSACTION OR TAKE OTHER MEASURES TO COMPLY WITH EXPORT CONTROL AND SANCTIONS LAWS."]
        },    
        {
            h1: 'PRIVACY',
            p: ["YOU ARE AWARE THAT, ON OCCASION, THE COMPANY MAY FIND IT NECESSARY TO GATHER PERSONAL DATA FROM YOU, ENCOMPASSING IDENTIFICATION DETAILS LIKE NAME, EMAIL ADDRESS, SHIPPING ADDRESS, AND CRYPTOCURRENCY WALLET INFORMATION. YOUR EXPLICIT ACKNOWLEDGMENT AND CONSENT EXTEND TO OUR POTENTIAL SHARING OF PERSONAL INFORMATION WITH THIRD-PARTY SERVICE PROVIDERS, AIDING US IN MEETING OPERATIONAL NEEDS, INCLUDING THIRD-PARTY PAYMENT PROCESSING, HOSTING, CLOUD, AND OTHER INFORMATION TECHNOLOGY SERVICES. FURTHERMORE, DISCLOSURE OF PERSONAL INFORMATION MAY OCCUR AS REQUIRED TO ADHERE TO APPLICABLE LAWS AND REGULATIONS, INCLUDING THOSE GOVERNED BY OFAC. THE COMPANY PLACES SIGNIFICANT IMPORTANCE ON THE DATA YOU PROVIDE AND COMMITS TO HANDLING IT WITH THE UTMOST SENSITIVITY. WE AFFIRM THAT UNDER NO CIRCUMSTANCES WILL WE SELL ANY PERSONAL INFORMATION TO THIRD PARTIES. THE COMPANY WILL DILIGENTLY EMPLOY COMMERCIALLY REASONABLE EFFORTS TO ESTABLISH TECHNICAL, ORGANIZATIONAL, AND PHYSICAL SAFEGUARDS TO PROTECT THE PERSONAL INFORMATION COLLECTED AND ENSURE DATA SECURITY. NEVERTHELESS, IT IS CRUCIAL TO RECOGNIZE THAT NO SECURITY MEASURES ARE FOOLPROOF, AND WE CANNOT PROVIDE AN ABSOLUTE GUARANTEE OF THE SECURITY OF YOUR PERSONAL INFORMATION. YOU ARE APPRISED OF THE INHERENT SECURITY RISKS ASSOCIATED WITH TRANSMITTING DATA, SUCH AS EMAILS, ADDRESSES, OR OTHER PERSONAL INFORMATION, VIA THE WEBSITE, AS COMPLETE PROTECTION AGAINST UNAUTHORIZED ACCESS BY THIRD PARTIES IS UNATTAINABLE. THE COMPANY DISCLAIMS ANY LIABILITY FOR DAMAGES RESULTING FROM SUCH SECURITY RISKS OR RELATED ACTS OF OMISSION ON OUR PART.."]
        }
            
    ]
    const [index, setIndex] = useState(0)
    const setIndex0 = () => {
        setIndex((index)=>0)
    }
    const setIndex1 = () => {
        setIndex((index)=>1)
    }
    const setIndex2 = () => {
        setIndex((index)=>2)
    }
    const setIndex3 = () => {
        setIndex((index)=>3)
    }
    const setIndex4 = () => {
        setIndex((index)=>4)
    }
    return ( 
        <div className="terms-page">
        <main className="terms">
            <div className="main-container container">
                <div className="page-title">
                    <div className="left-column">
                        <div className="page-title-text">
                            <span>///</span> TERMS
                        </div>
                         <div className="square"></div>
                    </div>
                    <div className="center-column">
                        <div className="square"></div>
                        <div className="square"></div>
                    </div>
                    <div className="right-column">
                        <div className="square"></div>
                        <div className="page-title-text">
                            LOADING...
                        </div>
                    </div>
                </div>
                <div className="terms-main-content">
                    <div className="left-column">
                        <div className="terms-list">
                            <span className="terms-item" onClick={setIndex0}>GENERAL TERMS & CONDITION</span>
                            <span className="terms-item" onClick={setIndex1}>DIGITAL ASSETS</span>
                            <span className="terms-item" onClick={setIndex2}>PHYSICAL PRODUCTS</span>
                            <span className="terms-item" onClick={setIndex3}>COVENANTS & RESTRICTIONS</span>
                            <span className="terms-item" onClick={setIndex4}>PRIVACY</span>
                        </div>
                    </div>
                    <div className="center-column">
                        <Swiper
                            className='terms-swiper'
                            slidesPerView={'auto'}
                            direction='vertical'
                            mousewheel={true}
                            freeMode={true}
                            scrollbar={{
                                el: '.swiper-scrollbar.swiper-scrollbar-vertical',
                                hide: false,
                            }}
                            modules={[Mousewheel, Scrollbar, FreeMode]}
                        >   
                            <SwiperSlide className="terms-text" style={{'maxHeight': 'fit-content'}}>
                                <h1 className="terms-text_h1">{termsList[index].h1}</h1>
                                {termsList[index].p.map((item) => {
                                    return <p className="terms-text_p">{item}</p>
                                })}
                            </SwiperSlide>
                                
                            
                        </Swiper>
                        <div className="terms-not-swiper">
                            <div   div className="terms-text" style={{'maxHeight': 'fit-content'}}>
                                <h1 className="terms-text_h1">{termsList[index].h1}</h1>
                                {termsList[index].p.map((item) => {
                                    return <p className="terms-text_p">{item}</p>
                                })}
                            </div>
                        </div>
                    </div>
                    <div className="right-column">
                        <div className="swiper-scrollbar swiper-scrollbar-vertical">
                            <div className="swiper-scrollbar-drag"></div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <Footer />
        </div>
     );
}
 
export default Terms;